http://localhost:8001/wp-json/wp/v2/pages


###
POST http://localhost:8001/wp-json/NFTorah/v1/purchases?_wpnonce=838365499e
Content-Type: application/json
//X-WP-Nonce: 838365499e
Referer: http://localhost:8001/purchase-a-letter/

{
    "hebrewName": "Moshe Nachum",
    "lastName": "Plotkin",
    "purchase": {
        "email" : "mplotkin@jewpaltz.com"
    },
    "letters" : [
        {
            "mothersName" : "Shoshanah"
        }
    ]
}

###
GET http://localhost:8001/wp-json/NFTorah/v1/torah/parshiot

###
https://api.sandbox.paypal.com/v2/checkout/orders/26N34189BD452215B

###
POST https://api-m.sandbox.paypal.com/v1/oauth2/token
accept: application/json
accept-language: en_US
Authorization: Basic QVNrc01kLUhtMFFKTkJ3bUY4ZllFY0F4ZV8xNG5jcWRzWGdrSUxXdEdldzBPMnM0SVFZUFpHcUp6SWpvSk56X2FDcDIwaG1ISVE1MWNWZTg6RUxFSU8xSm5jb295eHNRZmkyNHJWSEU1YmxGdHVoVGRRaG1jeFBPY25UbF9FQ21yS0Q1RFppN0dndnhYMVo3LTNnUDBEWUJXMGMzVVVGR0E=
content-type: application/x-www-form-urlencoded

grant_type=client_credentials

###
https://api.coinbase.com/v2/exchange-rates?currency=USD

###
https://api.binance.com/api/v3/avgPrice?symbol=ETHTUSD

###
POST https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($tokenAddress: Bytes!) {
    token( id: $tokenAddress ) {
        derivedETH
    }
}


 // Dai
{
    "tokenAddress": "0x6b175474e89094c44da98b954eedeac495271d0f"
}

###
https://api.etherscan.io/api?module=transaction&action=getstatus&txhash=0x8fc68f679f56c206e49425d4a805a463f93b8cda6170bad4708be3d993ca408c&apikey=RFV1SSHHYKCMXR5PXXB1ZWIYVQM7DU2PDY

###
https://api.etherscan.io/api?module=account&action=balance&address=0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae&tag=latest&apikey=RFV1SSHHYKCMXR5PXXB1ZWIYVQM7DU2PDY

###
POST https://rinkeby.infura.io/v3/0cbb0f724be040dd85aaf1ed5fbf9fb6

{
    "id":0,
    "jsonrpc":"2.0",
    "method":"eth_getTransactionByHash",
    "params":["0xafc2df606c88fc254e73bf65bb034a5d7fd2f01ddc3f3033beb0828b06e5f3e5"]
}
