http://localhost:8001/wp-json/wp/v2/pages


###
POST http://localhost:8001/wp-json/NFTorah/v1/purchases?_wpnonce=838365499e
Content-Type: application/json
//X-WP-Nonce: 838365499e
Referer: http://localhost:8001/purchase-a-letter/

{
    "hebrewName": "Moshe Nachum",
    "lastName": "Plotkin",
    "purchase": {
        "email" : "mplotkin@jewpaltz.com"
    },
    "letters" : [
        {
            "mothersName" : "Shoshanah"
        }
    ]
}

###
https://api.sandbox.paypal.com/v2/checkout/orders/26N34189BD452215B

###
POST https://api.paypal.com/v1/oauth2/token
accept: application/json
accept-language: en_US
authorization: basic 
content-type: application/x-www-form-urlencoded

grant_type=client_credentials

###