name: PHP Composer

on:
  push:
    branches: [ development, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    #- name: Validate composer.json and composer.lock
    #  run: composer validate --strict


    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress

    #- name: Install Node dependencies
    #  run: npm install --production
    
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
    
    - name: Remove File
      uses: JesseTG/rm@v1.0.2
      with:
        path: .gitignore
        # IT may be more prudent to have a separate .gitignore for this stage and copy it over the regular one instead of totally deleting the .gitignore file

    - name: Push to Staging Branch
      run: |
        git config user.email "jewpaltz@email.com"
        git config user.name "JewPaltz - Auto Push"
        git remote set-url origin https://Jewpaltz:${{secrets.ACCESS_TOKEN}}@github.com/Jewpaltz/NFTorah-Plugin.git
        git add .
        git commit -m "Build: ${{github.event.head_commit.message}}"
        git push origin HEAD:${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }} --force
